import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseDocument } from 'yaml';
import { z } from 'zod';
import { normalizeTemplate, promptTemplateSchema, type PromptTemplate } from '../src/domain/prompt';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const defaultPromptsDir = path.join(repoRoot, 'prompts');
const defaultOutputPath = path.join(repoRoot, 'src', 'data', 'generatedTemplates.ts');

const promptYamlSchema = z
  .object({
    id: z.string().min(1),
    title: z.string().min(1),
    description: z.string().min(1),
    template: z.string().min(1),
    category: z.string().min(1),
    tags: z.array(z.string().min(1)),
  })
  .strict();

export type RenderPromptsOptions = {
  promptsDir?: string;
  outputPath?: string;
  write?: boolean;
};

export class PromptRenderError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PromptRenderError';
  }
}

function isPromptFile(fileName: string) {
  return /\.ya?ml$/i.test(fileName);
}

function formatZodIssue(issue: z.ZodIssue) {
  const field = issue.path.length ? issue.path.join('.') : 'root';
  return `${field}: ${issue.message}`;
}

function formatGeneratedTemplates(templates: PromptTemplate[]) {
  return `// This file is generated by scripts/render-prompts.ts. Do not edit manually.
import type { PromptTemplate } from '../domain/prompt';

export const generatedTemplates = ${JSON.stringify(templates, null, 2)} satisfies PromptTemplate[];
`;
}

export async function renderPrompts(options: RenderPromptsOptions = {}): Promise<PromptTemplate[]> {
  const promptsDir = options.promptsDir ?? defaultPromptsDir;
  const outputPath = options.outputPath ?? defaultOutputPath;
  const write = options.write ?? true;

  const fileNames = (await readdir(promptsDir))
    .filter(isPromptFile)
    .sort((a, b) => a.localeCompare(b));
  if (!fileNames.length) {
    if (write) {
      await mkdir(path.dirname(outputPath), { recursive: true });
      await writeFile(outputPath, formatGeneratedTemplates([]), 'utf8');
    }
    return [];
  }

  const seenIds = new Map<string, string>();
  const templates: PromptTemplate[] = [];

  for (const fileName of fileNames) {
    const filePath = path.join(promptsDir, fileName);
    const source = await readFile(filePath, 'utf8');
    const document = parseDocument(source, { prettyErrors: false });

    if (document.errors.length) {
      const details = document.errors.map((error) => error.message).join('; ');
      throw new PromptRenderError(`${fileName}: YAML parse error: ${details}`);
    }

    const parsed = promptYamlSchema.safeParse(document.toJSON());
    if (!parsed.success) {
      const details = parsed.error.issues.map(formatZodIssue).join('; ');
      throw new PromptRenderError(`${fileName}: ${details}`);
    }

    const duplicateFile = seenIds.get(parsed.data.id);
    if (duplicateFile) {
      throw new PromptRenderError(
        `${fileName}: id "${parsed.data.id}" duplicates ${duplicateFile}. Each prompt id must be unique.`,
      );
    }
    seenIds.set(parsed.data.id, fileName);

    const normalized = promptTemplateSchema.parse(normalizeTemplate(parsed.data));
    templates.push(normalized);
  }

  templates.sort((a, b) => a.id.localeCompare(b.id));

  if (write) {
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, formatGeneratedTemplates(templates), 'utf8');
  }

  return templates;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  renderPrompts()
    .then((templates) => {
      console.log(
        `Rendered ${templates.length} prompt templates to ${path.relative(repoRoot, defaultOutputPath)}`,
      );
    })
    .catch((error: unknown) => {
      const message = error instanceof Error ? error.message : String(error);
      console.error(message);
      process.exit(1);
    });
}
